name: Claude Code Assistant

# Trigger on @claude mentions and new issues/PRs
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  claude-assist:
    # Run when @claude mentioned or new issue/PR
    if: >
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'pull_request' && github.event.action == 'opened')
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
      checks: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          # Personal Anthropic API key from repository secrets
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # GitHub token for API access
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Optional: Customize behavior
          # max_tokens: 4000
          # temperature: 0.1